# Docker 
# Build and push and image to the container registry

trigger:
  branches:
    include:
      - master
      - dev
  paths:
    exclude:
      - infrastructure/
pr:
  - master
  - dev

parameters:
  - name: DeployBranches
    displayName: Branches that should be deployed
    type: object
    default:
      - master
      - dev
  - name: resourceGroupName
    displayName: Resource Group Name
    type: string
    default: 'dfe-development'
  - name: azureSubscription
    displayName: The current Azure subscription 
    type: string
    default: 'AzureConnection'
  - name: containerRegistryName
    displayName: The container registry to push the image to
    type: string
    default: 's101eescrpublicapi.azurecr.io'

variables:
  BuildConfiguration: 'Release'
  IsBranchDeployable: ${{ containsValue(parameters.DeployBranches, variables['Build.SourceBranchName']) }}
  CI: true
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  azureSubscription: 'AzureConnection'
  dockerRegistryServiceConnection: '<SERVICE_CONNECTION_NAME>' 
  imageRepository: 'publicapi'
  dockerfilePath: '$(Build.SourcesDirectory)/docker/public-api/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


jobs:
  - job: 'API Backend'
    pool: 'ees-ubuntu2204-large'
    workspace:
      clean: all
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET 8.0 SDK'
        inputs:
          version: 8.0.x
          performMultiLevelLookup: true

      - task: 'DotNetCoreCLI@2'
        displayName: 'Restore'
        inputs:
          command: 'restore'
          projects: '**/GovUk.*/*csproj'
          feedsToUse: config
          nugetConfigPath: src/nuget.config

      - task: 'DotNetCoreCLI@2'
        displayName: 'Build'
        inputs:
          projects: '**/GovUk.*/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: 'DotNetCoreCLI@2'
        displayName: 'Test'
        inputs:
          command: 'test'
          projects: '**/GovUk.*[Tt]ests/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: 'DotNetCoreCLI@2'
        displayName: 'Publish Public Data API'
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/GovUk.Education.ExploreEducationStatistics.Public.Data.Api.csproj'
          arguments: '--self-contained true -r win-x64 --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)/public-data-api'
          zipAfterPublish: True

      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Public Data API Artifacts'
        inputs:
          artifactName: 'public_data_api'
          targetPath: '$(Build.ArtifactStagingDirectory)/public_data_api'


  - job: Build Public Data API
    displayName: Build Public Data API Docker Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      displayName: Build and publish image to Azure Container Registry
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: $(tag)