trigger:
  batch: true
  branches:
    include:
    - main
    - dev
  paths:
    include:
    - infrastructure/public-api/*
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    scriptType: 'bash' # You could also use Batch or PowerShell if desired
    scriptLocation: 'inlineScript'
    inlineScript: 'az bicep install'

- task: AzureCLI@2
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group validate --resource-group dfe-development --template-file Code/main.bicep --parameters Code/main.bicepparam'
    
- task: CopyFiles@2
  inputs:
    Contents: 'Code/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'