# Infrastructure 
# Check and build infrastructure 

trigger:
  batch: true
  branches:
    include:
    - main
    - dev
  paths:
    include:
    - infrastructure/public-api/*
pr: none

name: Deploy Public API Bicep files

variables:
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'dfe-development'
  location: 'uksouth'
  azureSubscription: 'AzureConnection'
  templateFile: '/public-api/main.bicep'
  templateParams: '/public-api/main.bicepparam'


pool:
  vmImage: $(vmImageName)

stages:
- stage: Build
  jobs:
  - job: Check_Infrastructure
    steps:
    ####### Check Infrastructure ########
    - checkout: self
    - task: CmdLine@2
      displayName: 'List source files'
      inputs:
        script: |
          echo "Structure of work folder of this pipeline:"
          tree $(Build.SourcesDirectory)

    - task: AzureCLI@2
      displayName: 'Install Bicep' 
      inputs:
        azureSubscription: $(azureSubscription) 
        scriptType: 'bash' # You could also use Batch or PowerShell if desired
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep install'

    - task: AzureCLI@2
      displayName: 'Validate bicep scripts' 
      inputs:
        azureSubscription: $(azureSubscription) 
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az deployment group validate --resource-group $(resourceGroupName) --template-file $(Build.SourcesDirectory)$(templateFile) --parameters $(Build.SourcesDirectory)$(templateParams)'
        
    - task: AzureCLI@2  
      displayName: 'Build bicep artifact for testing' 
      inputs:
        azureSubscription: $(azureSubscription) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file $(Build.SourcesDirectory)$(templateFile)'  

    - task: PublishBuildArtifacts@1
      displayName: 'Publish json artifact in pipeline'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container' 

# Begin Deployment Stage
# Environments Dev, Test, Pre-prod and Prod

- stage: Deploy_Dev
  displayName: 'Deploy to Development'
  condition: and(succeeded(), eq(variables.isDev, 'true'))
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Infrastructure'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          #### Task DEPLOY INFRASTRUCTURE ########
          - download: none
          - checkout: self
          - task: CmdLine@2
            displayName: 'List build source files'
            inputs:
              script: |
                echo "Structure of work folder of this pipeline:"
                echo "Main File = $(Build.SourcesDirectory)$(templateFile)"
                tree $(Build.SourcesDirectory)
          - task: AzureCLI@2
            displayName: 'Deploy bicep template to Azure'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group $(resourceGroupName) --template-file $(Build.SourcesDirectory)$(templateFile) --parameters $(Build.SourcesDirectory)$(templateParams)'

- stage: Deploy_Test
  displayName: 'Deploy to Testing'
  condition: and(succeeded(), eq(variables.isDev, 'true'))
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Infrastructure'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          #### Task DEPLOY INFRASTRUCTURE ########
          - download: none
          - checkout: self
          - task: CmdLine@2
            displayName: 'List build source files'
            inputs:
              script: |
                echo "Structure of work folder of this pipeline:"
                echo "Main File = $(Build.SourcesDirectory)$(templateFile)"
                tree $(Build.SourcesDirectory)
          - task: AzureCLI@2
            displayName: 'Deploy bicep template to Azure'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group $(resourceGroupName) --template-file $(Build.SourcesDirectory)$(templateFile) --parameters $(Build.SourcesDirectory)$(templateParams)'

- stage: Deploy_Pre-Prod
  displayName: 'Deploy to Pre-Prod'
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Infrastructure'
    environment: 'Pre-prod'
    strategy:
      runOnce:
        deploy:
          steps:
          #### Task DEPLOY INFRASTRUCTURE ########
          - download: none
          - checkout: self
          - task: CmdLine@2
            displayName: 'List build source files'
            inputs:
              script: |
                echo "Structure of work folder of this pipeline:"
                echo "Main File = $(Build.SourcesDirectory)$(templateFile)"
                tree $(Build.SourcesDirectory)
          - task: AzureCLI@2
            displayName: 'Deploy bicep template to Azure'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group $(resourceGroupName) --template-file $(Build.SourcesDirectory)$(templateFile) --parameters $(Build.SourcesDirectory)$(templateParams)'

- stage: Deploy_Prod
  displayName: 'Deploy to Production'
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Infrastructure'
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          #### Task DEPLOY INFRASTRUCTURE ########
          - download: none
          - checkout: self
          - task: CmdLine@2
            displayName: 'List build source files'
            inputs:
              script: |
                echo "Structure of work folder of this pipeline:"
                echo "Main File = $(Build.SourcesDirectory)$(templateFile)"
                tree $(Build.SourcesDirectory)
          - task: AzureCLI@2
            displayName: 'Deploy bicep template to Azure'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az deployment group create --resource-group $(resourceGroupName) --template-file $(Build.SourcesDirectory)$(templateFile) --parameters $(Build.SourcesDirectory)$(templateParams)'
